name: spectroscopy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - openpyxl
  - matplotlib
  - scipy
  - pillow
  - black
  - pip
  - pip:
      - BaselineRemoval
